# Generated by Django 4.1.5 on 2023-02-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productforuser',
            options={'verbose_name': 'سفارشات مشتری', 'verbose_name_plural': 'سفارشات مشتری ها'},
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='product',
        ),
        migrations.AddField(
            model_name='producttag',
            name='product',
            field=models.ManyToManyField(related_name='product_tags', to='product_module.product'),
        ),
    ]
