# Generated by Django 4.1.5 on 2023-02-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
