# Generated by Django 4.1.5 on 2023-02-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_alter_productcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslider',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSlider', to='product_module.product', verbose_name='محصول'),
        ),
    ]
