# Generated by Django 4.1.5 on 2023-02-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_product_is_slider_delete_productslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='product_module.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
