# Generated by Django 4.1.5 on 2023-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productforuser',
            name='amount',
        ),
        migrations.AddField(
            model_name='productforuser',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='تعداد محصول'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productforuser',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='productforuser',
            name='product',
            field=models.ManyToManyField(to='product_module.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(to='product_module.product', verbose_name='محصول'),
        ),
    ]
