# Generated by Django 4.1.5 on 2023-02-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_remove_productforuser_amount_productforuser_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productforuser',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='productforuser',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=545, on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول'),
            preserve_default=False,
        ),
    ]
