# Generated by Django 4.1.5 on 2023-02-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_remove_productforuser_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=8, verbose_name='تعداد محصول'),
            preserve_default=False,
        ),
    ]
