# Generated by Django 4.1.5 on 2023-03-03 18:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_module', '0013_product_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductForUser',
            new_name='ProductOrder',
        ),
    ]
