# Generated by Django 4.1.5 on 2023-03-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0014_rename_productforuser_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رنگ محصول'),
        ),
    ]
