# Generated by Django 4.1.5 on 2023-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0019_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'عکس محصول', 'verbose_name_plural': 'گالری عکس محصول'},
        ),
        migrations.AddField(
            model_name='productorder',
            name='color',
            field=models.CharField(default='None', max_length=21, verbose_name='رنگ محصول'),
        ),
    ]
