# Generated by Django 4.1.5 on 2023-01-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountModule', '0002_user_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
