# Generated by Django 4.1.5 on 2023-01-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountModule', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
